#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d 一 二 三 四 五 六 七 八 九 十
# bspc monitor -d          
bspc monitor -d 阳 乾 坤 震 巽 坎 离 艮 兑 阴
# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d Ⅰ Ⅱ Ⅲ Ⅳ Ⅴ Ⅵ Ⅶ Ⅷ Ⅸ Ⅹ
# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           18

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# color
bspc config normal_border_color \#00bbff
bspc config focused_border_color \#d7005f
bspc config active_border_color \#44ff00

# rule
bspc rule -a firefox desktop='^2'
bspc rule -a feh state=floating
bspc rule -a imv state=floating
bspc rule -a mpv state=floating
bspc rule -a TelegramDesktop state=floating desktop='^6'
bspc rule -a Zathura state=tiled
bspc rule -a "VirtualBox Manager" state=floating desktop='^8'

# bspc rule -a Pcmanfm state=floating
# bspc rule -a qv2ray state=floating
# bspc rule -a Screenkey manage=off
